/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("Articles.java-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("reflection.app.App")
}
